const nodes={local:{name:'Local',cpu:1,up:0,down:0,delay:0,cost:0,energy:1},edge:{name:'Edge',cpu:5,up:50,down:100,delay:20,cost:.001,energy:.4},cloud:{name:'Cloud',cpu:15,up:20,down:50,delay:100,cost:.003,energy:.2}};
const $=id=>document.getElementById(id);
function task(){return{data:+$('dataSize').value,cycles:+$('cpuCycles').value,output:+$('resultSize').value,deadline:+$('deadline').value}}
function calc(t,key){const n=nodes[key];const processing=t.cycles/n.cpu*1000;const latency=key==='local'?processing:(t.data/n.up*1000+n.delay+processing+t.output/n.down*1000);return{key,name:n.name,latency,cost:key==='local'?0:(t.data+t.output)*n.cost,energy:t.cycles*n.energy,met:latency<=t.deadline}}
function choose(results,strategy){if(['local','edge','cloud'].includes(strategy))return results.find(r=>r.key===strategy);if(strategy==='latency')return [...results].sort((a,b)=>a.latency-b.latency)[0];const valid=results.filter(r=>r.met);return valid.length?[...valid].sort((a,b)=>a.cost-b.cost||a.latency-b.latency)[0]:[...results].sort((a,b)=>a.latency-b.latency)[0]}
function render(){const t=task();const results=Object.keys(nodes).map(k=>calc(t,k));const picked=choose(results,$('strategy').value);$('selectedNode').textContent=picked.name.toUpperCase();$('metricLatency').textContent=picked.latency.toFixed(1);$('metricCost').textContent=picked.cost.toFixed(4);$('metricEnergy').textContent=picked.energy.toFixed(3);const margin=t.deadline-picked.latency;const badge=$('deadlineBadge');badge.className='deadline-badge '+(picked.met?'success':'fail');badge.firstElementChild.textContent=picked.met?'✓':'!';badge.querySelector('strong').textContent=picked.met?'Deadline met':'Deadline missed';$('deadlineDetail').textContent=picked.met?`${margin.toFixed(1)} ms 여유`:`${Math.abs(margin).toFixed(1)} ms 초과`;
  const fastest=Math.min(...results.map(r=>r.latency));const score=Math.max(35,Math.round(100-(picked.latency/Math.max(t.deadline,1))*18-(picked.cost*200)));$('score').textContent=score;$('scoreArc').style.strokeDashoffset=270*(1-score/100);
  const strategy=$('strategy').value;$('recommendReason').textContent=strategy==='deadline'?(picked.met?'마감 시간을 지키면서 비용이 가장 낮습니다.':'마감을 만족하는 노드가 없어 가장 빠른 노드를 선택했습니다.'):strategy==='latency'?'예상 지연 시간이 가장 짧은 노드입니다.':`${picked.name} 고정 전략의 결과입니다.`;
  const maxLatency=Math.max(...results.map(r=>r.latency));$('comparisonCards').innerHTML=results.map(r=>`<article class="compare-card ${r.key===picked.key?'selected':''}"><header><h3>${r.name}</h3>${r.key===picked.key?'<span class="selected-label">SELECTED</span>':''}</header><div class="bar-row"><div class="bar-label"><span>LATENCY</span><span>${r.latency.toFixed(1)} ms</span></div><div class="bar-track"><div class="bar-fill" style="width:${Math.max(4,r.latency/maxLatency*100)}%"></div></div></div><div class="card-stats"><div><small>COST</small><strong>${r.cost.toFixed(4)}</strong></div><div><small>ENERGY</small><strong>${r.energy.toFixed(2)} J</strong></div><div><small>DEADLINE</small><strong>${r.met?'PASS':'MISS'}</strong></div></div></article>`).join('')}
const controls=[['dataSize','dataValue',v=>`${(+v).toFixed(1)} MB`],['cpuCycles','cyclesValue',v=>`${(+v).toFixed(1)} G`],['resultSize','resultValue',v=>`${(+v).toFixed(1)} MB`],['deadline','deadlineValue',v=>`${v} ms`]];
controls.forEach(([input,output,format])=>$(input).addEventListener('input',()=>{$(output).textContent=format($(input).value);render()}));$('strategy').addEventListener('change',render);$('runBtn').addEventListener('click',()=>{render();document.querySelector('.result-panel').animate([{transform:'scale(.985)'},{transform:'scale(1)'}],{duration:300,easing:'ease-out'})});$('resetBtn').addEventListener('click',()=>{[['dataSize',5],['cpuCycles',1],['resultSize',.5],['deadline',500]].forEach(([id,v])=>{$(id).value=v;$(id).dispatchEvent(new Event('input'))});$('strategy').value='deadline';render()});render();
